// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="TinyYOLOHW_TinyYOLOHW,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.918000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=285,HLS_SYN_LUT=1096,HLS_VERSION=2025_1}" *)

module TinyYOLOHW (
        ap_clk,
        ap_rst_n,
        axi_in_TVALID,
        axi_out_TREADY,
        axi_in_TDATA,
        axi_in_TREADY,
        axi_in_TKEEP,
        axi_in_TSTRB,
        axi_in_TLAST,
        axi_out_TDATA,
        axi_out_TVALID,
        axi_out_TKEEP,
        axi_out_TSTRB,
        axi_out_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   axi_in_TVALID;
input   axi_out_TREADY;
input  [511:0] axi_in_TDATA;
output   axi_in_TREADY;
input  [63:0] axi_in_TKEEP;
input  [63:0] axi_in_TSTRB;
input  [0:0] axi_in_TLAST;
output  [511:0] axi_out_TDATA;
output   axi_out_TVALID;
output  [63:0] axi_out_TKEEP;
output  [63:0] axi_out_TSTRB;
output  [0:0] axi_out_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_ready;
reg    ap_block_state1_pp0_stage0_iter0;
wire    regslice_both_axi_out_V_data_V_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] streamin_last_fu_168_p1;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
wire   [31:0] img_width;
wire   [31:0] in_channels;
wire   [31:0] out_channels;
wire   [31:0] quant_M;
wire   [31:0] quant_n;
wire   [0:0] isMaxpool;
wire   [0:0] is_1x1;
wire   [31:0] stride;
reg    axi_in_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    axi_out_TDATA_blk_n;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] trunc_ln82_fu_173_p1;
wire   [31:0] tmp_2_fu_183_p3;
wire   [31:0] tmp_4_fu_197_p3;
wire   [31:0] tmp_6_fu_211_p3;
wire   [31:0] tmp_8_fu_225_p3;
wire   [31:0] tmp_s_fu_239_p3;
wire   [31:0] tmp_1_fu_253_p3;
wire   [31:0] tmp_3_fu_267_p3;
wire   [31:0] tmp_5_fu_281_p3;
wire   [31:0] tmp_7_fu_295_p3;
wire   [31:0] tmp_9_fu_309_p3;
wire   [31:0] tmp_10_fu_323_p3;
wire   [31:0] tmp_11_fu_337_p3;
wire   [31:0] tmp_12_fu_351_p3;
wire   [31:0] tmp_13_fu_365_p3;
wire   [31:0] tmp_14_fu_379_p3;
wire   [31:0] add_ln82_15_fu_387_p2;
wire   [31:0] add_ln82_14_fu_373_p2;
wire   [31:0] add_ln82_13_fu_359_p2;
wire   [31:0] add_ln82_12_fu_345_p2;
wire   [31:0] add_ln82_11_fu_331_p2;
wire   [31:0] add_ln82_10_fu_317_p2;
wire   [31:0] add_ln82_9_fu_303_p2;
wire   [31:0] add_ln82_8_fu_289_p2;
wire   [31:0] add_ln82_7_fu_275_p2;
wire   [31:0] add_ln82_6_fu_261_p2;
wire   [31:0] add_ln82_5_fu_247_p2;
wire   [31:0] add_ln82_4_fu_233_p2;
wire   [31:0] add_ln82_3_fu_219_p2;
wire   [31:0] add_ln82_2_fu_205_p2;
wire   [31:0] add_ln82_1_fu_191_p2;
wire   [31:0] add_ln82_fu_177_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_loop_init;
wire    regslice_both_axi_in_V_data_V_U_apdone_blk;
wire   [511:0] axi_in_TDATA_int_regslice;
wire    axi_in_TVALID_int_regslice;
reg    axi_in_TREADY_int_regslice;
wire    regslice_both_axi_in_V_data_V_U_ack_in;
wire    regslice_both_axi_in_V_keep_V_U_apdone_blk;
wire   [63:0] axi_in_TKEEP_int_regslice;
wire    regslice_both_axi_in_V_keep_V_U_vld_out;
wire    regslice_both_axi_in_V_keep_V_U_ack_in;
wire    regslice_both_axi_in_V_strb_V_U_apdone_blk;
wire   [63:0] axi_in_TSTRB_int_regslice;
wire    regslice_both_axi_in_V_strb_V_U_vld_out;
wire    regslice_both_axi_in_V_strb_V_U_ack_in;
wire    regslice_both_axi_in_V_last_V_U_apdone_blk;
wire   [0:0] axi_in_TLAST_int_regslice;
wire    regslice_both_axi_in_V_last_V_U_vld_out;
wire    regslice_both_axi_in_V_last_V_U_ack_in;
wire   [511:0] axi_out_TDATA_int_regslice;
reg    axi_out_TVALID_int_regslice;
wire    axi_out_TREADY_int_regslice;
wire    regslice_both_axi_out_V_data_V_U_vld_out;
wire    regslice_both_axi_out_V_keep_V_U_apdone_blk;
wire    regslice_both_axi_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_axi_out_V_keep_V_U_vld_out;
wire    regslice_both_axi_out_V_strb_V_U_apdone_blk;
wire   [63:0] axi_out_TSTRB_int_regslice;
wire    regslice_both_axi_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_axi_out_V_strb_V_U_vld_out;
wire    regslice_both_axi_out_V_last_V_U_apdone_blk;
wire    regslice_both_axi_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_axi_out_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

TinyYOLOHW_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .img_width(img_width),
    .in_channels(in_channels),
    .out_channels(out_channels),
    .quant_M(quant_M),
    .quant_n(quant_n),
    .isMaxpool(isMaxpool),
    .is_1x1(is_1x1),
    .stride(stride),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

TinyYOLOHW_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

TinyYOLOHW_regslice_both #(
    .DataWidth( 512 ))
regslice_both_axi_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axi_in_TDATA),
    .vld_in(axi_in_TVALID),
    .ack_in(regslice_both_axi_in_V_data_V_U_ack_in),
    .data_out(axi_in_TDATA_int_regslice),
    .vld_out(axi_in_TVALID_int_regslice),
    .ack_out(axi_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_axi_in_V_data_V_U_apdone_blk)
);

TinyYOLOHW_regslice_both #(
    .DataWidth( 64 ))
regslice_both_axi_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axi_in_TKEEP),
    .vld_in(axi_in_TVALID),
    .ack_in(regslice_both_axi_in_V_keep_V_U_ack_in),
    .data_out(axi_in_TKEEP_int_regslice),
    .vld_out(regslice_both_axi_in_V_keep_V_U_vld_out),
    .ack_out(axi_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_axi_in_V_keep_V_U_apdone_blk)
);

TinyYOLOHW_regslice_both #(
    .DataWidth( 64 ))
regslice_both_axi_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axi_in_TSTRB),
    .vld_in(axi_in_TVALID),
    .ack_in(regslice_both_axi_in_V_strb_V_U_ack_in),
    .data_out(axi_in_TSTRB_int_regslice),
    .vld_out(regslice_both_axi_in_V_strb_V_U_vld_out),
    .ack_out(axi_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_axi_in_V_strb_V_U_apdone_blk)
);

TinyYOLOHW_regslice_both #(
    .DataWidth( 1 ))
regslice_both_axi_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axi_in_TLAST),
    .vld_in(axi_in_TVALID),
    .ack_in(regslice_both_axi_in_V_last_V_U_ack_in),
    .data_out(axi_in_TLAST_int_regslice),
    .vld_out(regslice_both_axi_in_V_last_V_U_vld_out),
    .ack_out(axi_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_axi_in_V_last_V_U_apdone_blk)
);

TinyYOLOHW_regslice_both #(
    .DataWidth( 512 ))
regslice_both_axi_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axi_out_TDATA_int_regslice),
    .vld_in(axi_out_TVALID_int_regslice),
    .ack_in(axi_out_TREADY_int_regslice),
    .data_out(axi_out_TDATA),
    .vld_out(regslice_both_axi_out_V_data_V_U_vld_out),
    .ack_out(axi_out_TREADY),
    .apdone_blk(regslice_both_axi_out_V_data_V_U_apdone_blk)
);

TinyYOLOHW_regslice_both #(
    .DataWidth( 64 ))
regslice_both_axi_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axi_in_TKEEP_int_regslice),
    .vld_in(axi_out_TVALID_int_regslice),
    .ack_in(regslice_both_axi_out_V_keep_V_U_ack_in_dummy),
    .data_out(axi_out_TKEEP),
    .vld_out(regslice_both_axi_out_V_keep_V_U_vld_out),
    .ack_out(axi_out_TREADY),
    .apdone_blk(regslice_both_axi_out_V_keep_V_U_apdone_blk)
);

TinyYOLOHW_regslice_both #(
    .DataWidth( 64 ))
regslice_both_axi_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axi_out_TSTRB_int_regslice),
    .vld_in(axi_out_TVALID_int_regslice),
    .ack_in(regslice_both_axi_out_V_strb_V_U_ack_in_dummy),
    .data_out(axi_out_TSTRB),
    .vld_out(regslice_both_axi_out_V_strb_V_U_vld_out),
    .ack_out(axi_out_TREADY),
    .apdone_blk(regslice_both_axi_out_V_strb_V_U_apdone_blk)
);

TinyYOLOHW_regslice_both #(
    .DataWidth( 1 ))
regslice_both_axi_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(axi_in_TLAST_int_regslice),
    .vld_in(axi_out_TVALID_int_regslice),
    .ack_in(regslice_both_axi_out_V_last_V_U_ack_in_dummy),
    .data_out(axi_out_TLAST),
    .vld_out(regslice_both_axi_out_V_last_V_U_vld_out),
    .ack_out(axi_out_TREADY),
    .apdone_blk(regslice_both_axi_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready == 1'b0))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (*) begin
    if (((streamin_last_fu_168_p1 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        axi_in_TDATA_blk_n = axi_in_TVALID_int_regslice;
    end else begin
        axi_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        axi_in_TREADY_int_regslice = 1'b1;
    end else begin
        axi_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        axi_out_TDATA_blk_n = axi_out_TREADY_int_regslice;
    end else begin
        axi_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        axi_out_TVALID_int_regslice = 1'b1;
    end else begin
        axi_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln82_10_fu_317_p2 = (tmp_9_fu_309_p3 + 32'd1);

assign add_ln82_11_fu_331_p2 = (tmp_10_fu_323_p3 + 32'd1);

assign add_ln82_12_fu_345_p2 = (tmp_11_fu_337_p3 + 32'd1);

assign add_ln82_13_fu_359_p2 = (tmp_12_fu_351_p3 + 32'd1);

assign add_ln82_14_fu_373_p2 = (tmp_13_fu_365_p3 + 32'd1);

assign add_ln82_15_fu_387_p2 = (tmp_14_fu_379_p3 + 32'd1);

assign add_ln82_1_fu_191_p2 = (tmp_2_fu_183_p3 + 32'd1);

assign add_ln82_2_fu_205_p2 = (tmp_4_fu_197_p3 + 32'd1);

assign add_ln82_3_fu_219_p2 = (tmp_6_fu_211_p3 + 32'd1);

assign add_ln82_4_fu_233_p2 = (tmp_8_fu_225_p3 + 32'd1);

assign add_ln82_5_fu_247_p2 = (tmp_s_fu_239_p3 + 32'd1);

assign add_ln82_6_fu_261_p2 = (tmp_1_fu_253_p3 + 32'd1);

assign add_ln82_7_fu_275_p2 = (tmp_3_fu_267_p3 + 32'd1);

assign add_ln82_8_fu_289_p2 = (tmp_5_fu_281_p3 + 32'd1);

assign add_ln82_9_fu_303_p2 = (tmp_7_fu_295_p3 + 32'd1);

assign add_ln82_fu_177_p2 = (trunc_ln82_fu_173_p1 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_axi_out_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_axi_out_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (regslice_both_axi_out_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((axi_out_TREADY_int_regslice == 1'b0) | (axi_in_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((regslice_both_axi_out_V_data_V_U_apdone_blk == 1'b1) | (axi_out_TREADY_int_regslice == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign axi_in_TREADY = regslice_both_axi_in_V_data_V_U_ack_in;

assign axi_out_TDATA_int_regslice = {{{{{{{{{{{{{{{{add_ln82_15_fu_387_p2}, {add_ln82_14_fu_373_p2}}, {add_ln82_13_fu_359_p2}}, {add_ln82_12_fu_345_p2}}, {add_ln82_11_fu_331_p2}}, {add_ln82_10_fu_317_p2}}, {add_ln82_9_fu_303_p2}}, {add_ln82_8_fu_289_p2}}, {add_ln82_7_fu_275_p2}}, {add_ln82_6_fu_261_p2}}, {add_ln82_5_fu_247_p2}}, {add_ln82_4_fu_233_p2}}, {add_ln82_3_fu_219_p2}}, {add_ln82_2_fu_205_p2}}, {add_ln82_1_fu_191_p2}}, {add_ln82_fu_177_p2}};

assign axi_out_TSTRB_int_regslice = 'bx;

assign axi_out_TVALID = regslice_both_axi_out_V_data_V_U_vld_out;

assign streamin_last_fu_168_p1 = axi_in_TLAST_int_regslice;

assign tmp_10_fu_323_p3 = {{axi_in_TDATA_int_regslice[383:352]}};

assign tmp_11_fu_337_p3 = {{axi_in_TDATA_int_regslice[415:384]}};

assign tmp_12_fu_351_p3 = {{axi_in_TDATA_int_regslice[447:416]}};

assign tmp_13_fu_365_p3 = {{axi_in_TDATA_int_regslice[479:448]}};

assign tmp_14_fu_379_p3 = {{axi_in_TDATA_int_regslice[511:480]}};

assign tmp_1_fu_253_p3 = {{axi_in_TDATA_int_regslice[223:192]}};

assign tmp_2_fu_183_p3 = {{axi_in_TDATA_int_regslice[63:32]}};

assign tmp_3_fu_267_p3 = {{axi_in_TDATA_int_regslice[255:224]}};

assign tmp_4_fu_197_p3 = {{axi_in_TDATA_int_regslice[95:64]}};

assign tmp_5_fu_281_p3 = {{axi_in_TDATA_int_regslice[287:256]}};

assign tmp_6_fu_211_p3 = {{axi_in_TDATA_int_regslice[127:96]}};

assign tmp_7_fu_295_p3 = {{axi_in_TDATA_int_regslice[319:288]}};

assign tmp_8_fu_225_p3 = {{axi_in_TDATA_int_regslice[159:128]}};

assign tmp_9_fu_309_p3 = {{axi_in_TDATA_int_regslice[351:320]}};

assign tmp_s_fu_239_p3 = {{axi_in_TDATA_int_regslice[191:160]}};

assign trunc_ln82_fu_173_p1 = axi_in_TDATA_int_regslice[31:0];

endmodule //TinyYOLOHW
