# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.srcs/sources_1/ip/bram_weights_1/bram_weights_1.xci
# IP: The module: 'bram_weights_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.gen/sources_1/ip/bram_weights_1/bram_weights_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_weights_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.srcs/sources_1/ip/bram_weights_1/bram_weights_1.xci
# IP: The module: 'bram_weights_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.gen/sources_1/ip/bram_weights_1/bram_weights_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_weights_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
