# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_user.xdc

# IP: /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.srcs/sources_1/ip/bram_bias_1/bram_bias_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_bias_1 || ORIG_REF_NAME==bram_bias_1} -quiet] -quiet

# IP: /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.srcs/sources_1/ip/bram_weights_1/bram_weights_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bram_weights_1 || ORIG_REF_NAME==bram_weights_1} -quiet] -quiet

# XDC: /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.gen/sources_1/ip/bram_bias_1/bram_bias_1_ooc.xdc

# XDC: /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.gen/sources_1/ip/bram_weights_1/bram_weights_1_ooc.xdc
