# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/TinyYOLOHW_ex.runs/synth_1/TinyYOLOHW.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param general.usePosixSpawnForFork 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/TinyYOLOHW_ex.cache/wt [current_project]
set_property parent.project_path /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/TinyYOLOHW_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.4 [current_project]
set_property ip_output_repo /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/TinyYOLOHW_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_example.sv
  /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_example_counter.sv
  /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_example_number_generator.sv
  /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_example_vadd_axis.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/compute_kernel_top.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/conv_3x3.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/lib/dsp_wrap_int8.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/kernel_window.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/lib/line_buffer.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/output_packer.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/parameter_loader.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/partial_sum_accumalator.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/pixel_serializer.sv
  /media/ubuntu/T7/projects/arm-bharat/hdl/quantizer.sv
}
read_verilog -library xil_defaultlib {
  /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_control_s_axi.v
  /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW.v
}
read_ip -quiet /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci

read_ip -quiet /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.srcs/sources_1/ip/bram_bias_1/bram_bias_1.xci
set_property used_in_implementation false [get_files -all /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.gen/sources_1/ip/bram_bias_1/bram_bias_1_ooc.xdc]

read_ip -quiet /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.srcs/sources_1/ip/bram_weights_1/bram_weights_1.xci
set_property used_in_implementation false [get_files -all /media/ubuntu/T7/projects/arm-bharat/Tiny_YOLO_HW/Tiny_YOLO_HW.gen/sources_1/ip/bram_weights_1/bram_weights_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_ooc.xdc
set_property used_in_implementation false [get_files /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_ooc.xdc]

read_xdc /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_user.xdc
set_property used_in_implementation false [get_files /media/ubuntu/T7/projects/arm-bharat/TinyYOLOHW_ex/imports/TinyYOLOHW_user.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top TinyYOLOHW -part xck26-sfvc784-2LV-c -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TinyYOLOHW.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file TinyYOLOHW_utilization_synth.rpt -pb TinyYOLOHW_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
