-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity TinyYOLOHW is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    axi_in_TVALID : IN STD_LOGIC;
    axi_out_TREADY : IN STD_LOGIC;
    axi_in_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    axi_in_TREADY : OUT STD_LOGIC;
    axi_in_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    axi_in_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
    axi_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    axi_out_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    axi_out_TVALID : OUT STD_LOGIC;
    axi_out_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    axi_out_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    axi_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of TinyYOLOHW is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "TinyYOLOHW_TinyYOLOHW,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.918000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=285,HLS_SYN_LUT=1096,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111100000";

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal regslice_both_axi_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal streamin_last_fu_168_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal img_width : STD_LOGIC_VECTOR (31 downto 0);
    signal in_channels : STD_LOGIC_VECTOR (31 downto 0);
    signal out_channels : STD_LOGIC_VECTOR (31 downto 0);
    signal quant_M : STD_LOGIC_VECTOR (31 downto 0);
    signal quant_n : STD_LOGIC_VECTOR (31 downto 0);
    signal isMaxpool : STD_LOGIC_VECTOR (0 downto 0);
    signal is_1x1 : STD_LOGIC_VECTOR (0 downto 0);
    signal stride : STD_LOGIC_VECTOR (31 downto 0);
    signal axi_in_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal axi_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln82_fu_173_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_183_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_197_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_211_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_225_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_239_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_253_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_267_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_281_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_295_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_309_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_323_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_337_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_fu_351_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_fu_365_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_fu_379_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_15_fu_387_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_14_fu_373_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_13_fu_359_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_12_fu_345_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_11_fu_331_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_10_fu_317_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_9_fu_303_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_8_fu_289_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_7_fu_275_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_6_fu_261_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_5_fu_247_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_4_fu_233_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_3_fu_219_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_2_fu_205_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_1_fu_191_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln82_fu_177_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal regslice_both_axi_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal axi_in_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal axi_in_TVALID_int_regslice : STD_LOGIC;
    signal axi_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_axi_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_axi_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal axi_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_axi_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_axi_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_axi_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal axi_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_axi_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_axi_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_axi_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal axi_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_axi_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_axi_in_V_last_V_U_ack_in : STD_LOGIC;
    signal axi_out_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal axi_out_TVALID_int_regslice : STD_LOGIC;
    signal axi_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_axi_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_axi_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_axi_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_axi_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_axi_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal axi_out_TSTRB_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_axi_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_axi_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_axi_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_axi_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_axi_out_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component TinyYOLOHW_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        img_width : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_channels : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_channels : OUT STD_LOGIC_VECTOR (31 downto 0);
        quant_M : OUT STD_LOGIC_VECTOR (31 downto 0);
        quant_n : OUT STD_LOGIC_VECTOR (31 downto 0);
        isMaxpool : OUT STD_LOGIC_VECTOR (0 downto 0);
        is_1x1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        stride : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component TinyYOLOHW_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component TinyYOLOHW_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    control_s_axi_U : component TinyYOLOHW_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        img_width => img_width,
        in_channels => in_channels,
        out_channels => out_channels,
        quant_M => quant_M,
        quant_n => quant_n,
        isMaxpool => isMaxpool,
        is_1x1 => is_1x1,
        stride => stride,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    flow_control_loop_pipe_U : component TinyYOLOHW_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);

    regslice_both_axi_in_V_data_V_U : component TinyYOLOHW_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => axi_in_TDATA,
        vld_in => axi_in_TVALID,
        ack_in => regslice_both_axi_in_V_data_V_U_ack_in,
        data_out => axi_in_TDATA_int_regslice,
        vld_out => axi_in_TVALID_int_regslice,
        ack_out => axi_in_TREADY_int_regslice,
        apdone_blk => regslice_both_axi_in_V_data_V_U_apdone_blk);

    regslice_both_axi_in_V_keep_V_U : component TinyYOLOHW_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => axi_in_TKEEP,
        vld_in => axi_in_TVALID,
        ack_in => regslice_both_axi_in_V_keep_V_U_ack_in,
        data_out => axi_in_TKEEP_int_regslice,
        vld_out => regslice_both_axi_in_V_keep_V_U_vld_out,
        ack_out => axi_in_TREADY_int_regslice,
        apdone_blk => regslice_both_axi_in_V_keep_V_U_apdone_blk);

    regslice_both_axi_in_V_strb_V_U : component TinyYOLOHW_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => axi_in_TSTRB,
        vld_in => axi_in_TVALID,
        ack_in => regslice_both_axi_in_V_strb_V_U_ack_in,
        data_out => axi_in_TSTRB_int_regslice,
        vld_out => regslice_both_axi_in_V_strb_V_U_vld_out,
        ack_out => axi_in_TREADY_int_regslice,
        apdone_blk => regslice_both_axi_in_V_strb_V_U_apdone_blk);

    regslice_both_axi_in_V_last_V_U : component TinyYOLOHW_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => axi_in_TLAST,
        vld_in => axi_in_TVALID,
        ack_in => regslice_both_axi_in_V_last_V_U_ack_in,
        data_out => axi_in_TLAST_int_regslice,
        vld_out => regslice_both_axi_in_V_last_V_U_vld_out,
        ack_out => axi_in_TREADY_int_regslice,
        apdone_blk => regslice_both_axi_in_V_last_V_U_apdone_blk);

    regslice_both_axi_out_V_data_V_U : component TinyYOLOHW_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => axi_out_TDATA_int_regslice,
        vld_in => axi_out_TVALID_int_regslice,
        ack_in => axi_out_TREADY_int_regslice,
        data_out => axi_out_TDATA,
        vld_out => regslice_both_axi_out_V_data_V_U_vld_out,
        ack_out => axi_out_TREADY,
        apdone_blk => regslice_both_axi_out_V_data_V_U_apdone_blk);

    regslice_both_axi_out_V_keep_V_U : component TinyYOLOHW_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => axi_in_TKEEP_int_regslice,
        vld_in => axi_out_TVALID_int_regslice,
        ack_in => regslice_both_axi_out_V_keep_V_U_ack_in_dummy,
        data_out => axi_out_TKEEP,
        vld_out => regslice_both_axi_out_V_keep_V_U_vld_out,
        ack_out => axi_out_TREADY,
        apdone_blk => regslice_both_axi_out_V_keep_V_U_apdone_blk);

    regslice_both_axi_out_V_strb_V_U : component TinyYOLOHW_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => axi_out_TSTRB_int_regslice,
        vld_in => axi_out_TVALID_int_regslice,
        ack_in => regslice_both_axi_out_V_strb_V_U_ack_in_dummy,
        data_out => axi_out_TSTRB,
        vld_out => regslice_both_axi_out_V_strb_V_U_vld_out,
        ack_out => axi_out_TREADY,
        apdone_blk => regslice_both_axi_out_V_strb_V_U_apdone_blk);

    regslice_both_axi_out_V_last_V_U : component TinyYOLOHW_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => axi_in_TLAST_int_regslice,
        vld_in => axi_out_TVALID_int_regslice,
        ack_in => regslice_both_axi_out_V_last_V_U_ack_in_dummy,
        data_out => axi_out_TLAST,
        vld_out => regslice_both_axi_out_V_last_V_U_vld_out,
        ack_out => axi_out_TREADY,
        apdone_blk => regslice_both_axi_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready = ap_const_logic_0))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln82_10_fu_317_p2 <= std_logic_vector(unsigned(tmp_9_fu_309_p3) + unsigned(ap_const_lv32_1));
    add_ln82_11_fu_331_p2 <= std_logic_vector(unsigned(tmp_10_fu_323_p3) + unsigned(ap_const_lv32_1));
    add_ln82_12_fu_345_p2 <= std_logic_vector(unsigned(tmp_11_fu_337_p3) + unsigned(ap_const_lv32_1));
    add_ln82_13_fu_359_p2 <= std_logic_vector(unsigned(tmp_12_fu_351_p3) + unsigned(ap_const_lv32_1));
    add_ln82_14_fu_373_p2 <= std_logic_vector(unsigned(tmp_13_fu_365_p3) + unsigned(ap_const_lv32_1));
    add_ln82_15_fu_387_p2 <= std_logic_vector(unsigned(tmp_14_fu_379_p3) + unsigned(ap_const_lv32_1));
    add_ln82_1_fu_191_p2 <= std_logic_vector(unsigned(tmp_2_fu_183_p3) + unsigned(ap_const_lv32_1));
    add_ln82_2_fu_205_p2 <= std_logic_vector(unsigned(tmp_4_fu_197_p3) + unsigned(ap_const_lv32_1));
    add_ln82_3_fu_219_p2 <= std_logic_vector(unsigned(tmp_6_fu_211_p3) + unsigned(ap_const_lv32_1));
    add_ln82_4_fu_233_p2 <= std_logic_vector(unsigned(tmp_8_fu_225_p3) + unsigned(ap_const_lv32_1));
    add_ln82_5_fu_247_p2 <= std_logic_vector(unsigned(tmp_s_fu_239_p3) + unsigned(ap_const_lv32_1));
    add_ln82_6_fu_261_p2 <= std_logic_vector(unsigned(tmp_1_fu_253_p3) + unsigned(ap_const_lv32_1));
    add_ln82_7_fu_275_p2 <= std_logic_vector(unsigned(tmp_3_fu_267_p3) + unsigned(ap_const_lv32_1));
    add_ln82_8_fu_289_p2 <= std_logic_vector(unsigned(tmp_5_fu_281_p3) + unsigned(ap_const_lv32_1));
    add_ln82_9_fu_303_p2 <= std_logic_vector(unsigned(tmp_7_fu_295_p3) + unsigned(ap_const_lv32_1));
    add_ln82_fu_177_p2 <= std_logic_vector(unsigned(trunc_ln82_fu_173_p1) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_pp0_stage0_iter0, regslice_both_axi_out_V_data_V_U_apdone_blk, ap_block_state2_pp0_stage0_iter1, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_axi_out_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_pp0_stage0_iter0, regslice_both_axi_out_V_data_V_U_apdone_blk, ap_block_state2_pp0_stage0_iter1, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_axi_out_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_pp0_stage0_iter0, regslice_both_axi_out_V_data_V_U_apdone_blk, ap_block_state2_pp0_stage0_iter1, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_axi_out_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(axi_in_TVALID_int_regslice, axi_out_TREADY_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((axi_out_TREADY_int_regslice = ap_const_logic_0) or (axi_in_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(regslice_both_axi_out_V_data_V_U_apdone_blk, axi_out_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((regslice_both_axi_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (axi_out_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, streamin_last_fu_168_p1, ap_start_int)
    begin
        if (((streamin_last_fu_168_p1 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_exit_ready_pp0_iter1_reg, ap_block_pp0_stage0_subdone, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    axi_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_start_int, axi_in_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            axi_in_TDATA_blk_n <= axi_in_TVALID_int_regslice;
        else 
            axi_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    axi_in_TREADY <= regslice_both_axi_in_V_data_V_U_ack_in;

    axi_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            axi_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            axi_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    axi_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_start_int, axi_out_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            axi_out_TDATA_blk_n <= axi_out_TREADY_int_regslice;
        else 
            axi_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    axi_out_TDATA_int_regslice <= (((((((((((((((add_ln82_15_fu_387_p2 & add_ln82_14_fu_373_p2) & add_ln82_13_fu_359_p2) & add_ln82_12_fu_345_p2) & add_ln82_11_fu_331_p2) & add_ln82_10_fu_317_p2) & add_ln82_9_fu_303_p2) & add_ln82_8_fu_289_p2) & add_ln82_7_fu_275_p2) & add_ln82_6_fu_261_p2) & add_ln82_5_fu_247_p2) & add_ln82_4_fu_233_p2) & add_ln82_3_fu_219_p2) & add_ln82_2_fu_205_p2) & add_ln82_1_fu_191_p2) & add_ln82_fu_177_p2);
    axi_out_TSTRB_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    axi_out_TVALID <= regslice_both_axi_out_V_data_V_U_vld_out;

    axi_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            axi_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            axi_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    streamin_last_fu_168_p1 <= axi_in_TLAST_int_regslice;
    tmp_10_fu_323_p3 <= axi_in_TDATA_int_regslice(383 downto 352);
    tmp_11_fu_337_p3 <= axi_in_TDATA_int_regslice(415 downto 384);
    tmp_12_fu_351_p3 <= axi_in_TDATA_int_regslice(447 downto 416);
    tmp_13_fu_365_p3 <= axi_in_TDATA_int_regslice(479 downto 448);
    tmp_14_fu_379_p3 <= axi_in_TDATA_int_regslice(511 downto 480);
    tmp_1_fu_253_p3 <= axi_in_TDATA_int_regslice(223 downto 192);
    tmp_2_fu_183_p3 <= axi_in_TDATA_int_regslice(63 downto 32);
    tmp_3_fu_267_p3 <= axi_in_TDATA_int_regslice(255 downto 224);
    tmp_4_fu_197_p3 <= axi_in_TDATA_int_regslice(95 downto 64);
    tmp_5_fu_281_p3 <= axi_in_TDATA_int_regslice(287 downto 256);
    tmp_6_fu_211_p3 <= axi_in_TDATA_int_regslice(127 downto 96);
    tmp_7_fu_295_p3 <= axi_in_TDATA_int_regslice(319 downto 288);
    tmp_8_fu_225_p3 <= axi_in_TDATA_int_regslice(159 downto 128);
    tmp_9_fu_309_p3 <= axi_in_TDATA_int_regslice(351 downto 320);
    tmp_s_fu_239_p3 <= axi_in_TDATA_int_regslice(191 downto 160);
    trunc_ln82_fu_173_p1 <= axi_in_TDATA_int_regslice(32 - 1 downto 0);
end behav;
