


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package axi_out_vip_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter axi_out_vip_VIP_INTERFACE_MODE     = 2;
      parameter axi_out_vip_VIP_SIGNAL_SET         = 8'b00011011;
      parameter axi_out_vip_VIP_DATA_WIDTH         = 512;
      parameter axi_out_vip_VIP_ID_WIDTH           = 1;
      parameter axi_out_vip_VIP_DEST_WIDTH         = 1;
      parameter axi_out_vip_VIP_USER_WIDTH         = 0;
      parameter axi_out_vip_VIP_USER_BITS_PER_BYTE = 0;
      parameter axi_out_vip_VIP_HAS_TREADY         = 1;
      parameter axi_out_vip_VIP_HAS_TSTRB          = 0;
      parameter axi_out_vip_VIP_HAS_TKEEP          = 1;
      parameter axi_out_vip_VIP_HAS_TLAST          = 1;
      parameter axi_out_vip_VIP_HAS_ACLKEN         = 0;
      parameter axi_out_vip_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(axi_out_vip_VIP_SIGNAL_SET, 
                        axi_out_vip_VIP_DEST_WIDTH,
                        axi_out_vip_VIP_DATA_WIDTH,
                        axi_out_vip_VIP_ID_WIDTH,
                        axi_out_vip_VIP_USER_WIDTH, 
                        axi_out_vip_VIP_USER_BITS_PER_BYTE,
                        axi_out_vip_VIP_HAS_ARESETN) axi_out_vip_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      axi_out_vip_slv_t  axi_out_vip_slv;
//      initial begin : START_axi_out_vip_SLAVE
//        axi_out_vip_slv = new("axi_out_vip_slv", `axi_out_vip_PATH_TO_INTERFACE);
//        axi_out_vip_slv.start_slave();
//      end

endpackage : axi_out_vip_pkg
