#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Feb 07 16:48:35 IST 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/media/ubuntu/T7/Xilinx-tools/2025.1/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_14 -L mult_gen_v12_0_23 -L xbip_dsp48_wrapper_v3_0_7 -L xbip_pipe_v3_0_10 -L xbip_multadd_v3_0_22 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_conv_3x3_behav xil_defaultlib.tb_conv_3x3 xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_14 -L mult_gen_v12_0_23 -L xbip_dsp48_wrapper_v3_0_7 -L xbip_pipe_v3_0_10 -L xbip_multadd_v3_0_22 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_conv_3x3_behav xil_defaultlib.tb_conv_3x3 xil_defaultlib.glbl -log elaborate.log

