

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
		"CDFG" : "TinyYOLOHW",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "img_width", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_channels", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_channels", "Type" : "None", "Direction" : "I"},
			{"Name" : "quant_M", "Type" : "None", "Direction" : "I"},
			{"Name" : "quant_n", "Type" : "None", "Direction" : "I"},
			{"Name" : "isMaxpool", "Type" : "None", "Direction" : "I"},
			{"Name" : "is_1x1", "Type" : "None", "Direction" : "I"},
			{"Name" : "stride", "Type" : "None", "Direction" : "I"},
			{"Name" : "axi_in_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "axi_in",
				"BlockSignal" : [
					{"Name" : "axi_in_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "axi_in_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "axi_in"},
			{"Name" : "axi_in_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "axi_in"},
			{"Name" : "axi_in_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "axi_in"},
			{"Name" : "axi_out_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "axi_out",
				"BlockSignal" : [
					{"Name" : "axi_out_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "axi_out_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "axi_out"},
			{"Name" : "axi_out_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "axi_out"},
			{"Name" : "axi_out_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "axi_out"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_96_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.flow_control_loop_pipe_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_axi_in_V_data_V_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_axi_in_V_keep_V_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_axi_in_V_strb_V_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_axi_in_V_last_V_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_axi_out_V_data_V_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_axi_out_V_keep_V_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_axi_out_V_strb_V_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_axi_out_V_last_V_U", "Parent" : "0"}]}
